FROM python:latest

# Folder on the container
WORKDIR /code

COPY ../../requirements.txt /code
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80" ]
